// Auth Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

// Alert Types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Profile Types
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const UPLOAD_PROFILE_IMAGE_SUCCESS = 'UPLOAD_PROFILE_IMAGE_SUCCESS';
export const UPLOAD_PROFILE_IMAGE_FAIL = 'UPLOAD_PROFILE_IMAGE_FAIL';

// Sponsorship Types
export const GET_SPONSORSHIPS = 'GET_SPONSORSHIPS';
export const GET_SPONSORSHIP = 'GET_SPONSORSHIP';
export const CREATE_SPONSORSHIP = 'CREATE_SPONSORSHIP';
export const UPDATE_SPONSORSHIP = 'UPDATE_SPONSORSHIP';
export const DELETE_SPONSORSHIP = 'DELETE_SPONSORSHIP';
export const SPONSORSHIP_ERROR = 'SPONSORSHIP_ERROR';
export const SPONSORSHIP_LOADING = 'SPONSORSHIP_LOADING';
export const CONFIRM_SPONSORSHIP = 'CONFIRM_SPONSORSHIP';
export const UPLOAD_PROOF = 'UPLOAD_PROOF';

// Message Types
export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGE_THREAD = 'GET_MESSAGE_THREAD';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const MESSAGE_LOADING = 'MESSAGE_LOADING';
export const GET_UNREAD_MESSAGES_COUNT = 'GET_UNREAD_MESSAGES_COUNT';
export const MARK_MESSAGE_READ = 'MARK_MESSAGE_READ';

// Notification Types
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_UNREAD_NOTIFICATIONS_COUNT = 'GET_UNREAD_NOTIFICATIONS_COUNT';
export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const NOTIFICATION_LOADING = 'NOTIFICATION_LOADING';

// Report Types
export const GET_REPORTS = 'GET_REPORTS';
export const GET_REPORT = 'GET_REPORT';
export const GENERATE_REPORT = 'GENERATE_REPORT';
export const REPORT_ERROR = 'REPORT_ERROR';
export const REPORT_LOADING = 'REPORT_LOADING';